metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression
  #_source.enabled: false

setup.kibana: 
  host: "KIBANA_ADDRESS"

output.elasticsearch:
  hosts: ["ES_ADDRESS"]
